version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'

  order-service:
    build:
      context: ./backend/order-service
    container_name: order-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/pizza-shop
    ports:
      - '3001:3001'
    depends_on:
      - mongo

  menu-service:
    build:
      context: ./backend/menu-service
    container_name: menu-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/pizza-shop
    ports:
      - '3002:3002'
    depends_on:
      - mongo

  chef-service:
    build:
      context: ./backend/chef-service
    container_name: chef-service
    environment:
      - MONGO_URI=mongodb://mongo:27017/pizza-shop
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '3003:3003'
    depends_on:
      - mongo
      - redis

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - '3000:80'

volumes:
  mongo_data:
