apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: avishkmonga/frontend:latest
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_ORDER_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REACT_APP_ORDER_SERVICE_URL
            - name: REACT_APP_MENU_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REACT_APP_MENU_SERVICE_URL
            - name: REACT_APP_CHEF_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: REACT_APP_CHEF_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
